version: 0.2
env:
  variables:
     APPVERSION: "v0.1.0"
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
       - echo Installing Virtualenv and Zappa
       - pip install zappa virtualenv
       - echo Installing requirements
       - pip install -r requirements.txt
       - echo Installing Zappa
       - pip install zappa
  build:
    commands:
       - echo Creating Virtualenv Folder
       - virtualenv venv
       - echo Building Virtualenv
       - source venv/bin/activate
       - pip install -r requirements.txt
       - deactivate
       - echo Deploying To Dev
       - zappa update dev

