version: 0.2
env:
  variables:
    APPVERSION: "v0.2.0"
    AWS_REGION: sa-east-1
    APPNAME: "curl-to-ps"
  secrets-manager:
    AWS_ACCESS_KEY: zappa-keys:zappa-access-key
    AWS_SECRET_KEY: zappa-keys:zappa-secret-key
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
       - echo Configuring Profile
       - mkdir ~/.aws
       - touch ~/.aws/credentials
       - echo "[zappa]" >> ~/.aws/credentials
       - echo "aws_access_key_id = $AWS_ACCESS_KEY" >> ~/.aws/credentials
       - echo "aws_secret_access_key = $AWS_SECRET_KEY" >> ~/.aws/credentials
       - touch ~/.aws/config
       - echo "[profile zappa]" >> ~/.aws/config
       - echo "region = $AWS_REGION" >> ~/.aws/config
       - echo Installing Virtualenv
       - pip install virtualenv
       - virtualenv venv
  build:
    commands:
       - echo Installing requirements and zappa
       - source venv/bin/activate
       - pip install -r requirements.txt
       - echo Installing Zappa
       - pip install zappa
       - echo Updating "$STAGE"
       - zappa update "$STAGE"
  post_build:
    commands:
       - echo Setting up ENVARS in Lambda
       - aws lambda update-function-configuration --function-name "$APPNAME-$STAGE" --environment "{\"Variables\":{\"APPVERSION\":\"$APPVERSION\",\"DYNAMODB_TABLE\":\"$DYNAMODB_TABLE\"}}"
